"use client";

import { useEffect, useMemo, useRef, useState, type ReactNode, type SetStateAction } from "react";
import { ArrowDownload24Regular, ArrowRight24Regular, CheckmarkCircle24Regular, ClipboardTask24Regular, CloudCheckmark24Regular, History24Regular, LockClosed24Regular, Person24Regular, ShieldCheckmark24Regular, Warning24Regular } from "@fluentui/react-icons";
import { adminActivities, auditIntegrations, governanceAuditSeed, type AdminActivity, type AdminGovernance, type AdminRisk, type GovernanceAudit } from "@/data/admin-audit";

type AuditTab = "activity" | "comparison" | "governance" | "reports";
const risks: (AdminRisk | "All")[] = ["All", "Critical", "High", "Medium", "Low"];
const riskClass = (risk: AdminRisk) => `aga-risk aga-${risk.toLowerCase()}`;
const timestamp = () => new Date().toISOString().slice(0, 16).replace("T", " ");

function useAuditStored<T>(key: string, seed: T): [T, (next: SetStateAction<T>) => void] {
  const [value, setValue] = useState<T>(seed);
  const hydrated = useRef(false);
  useEffect(() => { try { const raw = window.localStorage.getItem(key); if (raw) setValue(JSON.parse(raw) as T); } catch { /* local demo storage is optional */ } hydrated.current = true; }, [key]);
  useEffect(() => { if (!hydrated.current) return; try { window.localStorage.setItem(key, JSON.stringify(value)); } catch { /* local demo storage is optional */ } }, [key, value]);
  return [value, setValue];
}

function downloadCsv(events: AdminActivity[], name: string) {
  const headings = ["Timestamp", "Administrator", "Service", "Admin center", "Action", "Target", "Previous value", "New value", "IP address", "Result", "Risk", "Governance", "Justification"];
  const esc = (value: string) => `"${value.replaceAll('"', '""')}"`;
  const rows = events.map((item) => [item.timestamp, item.administrator, item.service, item.center, item.action, item.target, item.previous, item.current, item.ip, item.result, item.risk, item.governance, item.reason].map(esc).join(","));
  const blob = new Blob([[headings.map(esc).join(","), ...rows].join("\r\n")], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1_000);
}

export function AdminAuditWorkspace({ notify, onOpenReport }: { notify: (message: string) => void; onOpenReport: (reportId: string) => void }) {
  const [activities, setActivities] = useAuditStored<AdminActivity[]>("pr360.admin-audit.activities", adminActivities);
  const [governanceAudit, setGovernanceAudit] = useAuditStored<GovernanceAudit[]>("pr360.admin-audit.evidence", governanceAuditSeed);
  const [selectedId, setSelectedId] = useState(adminActivities[0].id);
  const [tab, setTab] = useState<AuditTab>("activity");
  const [risk, setRisk] = useState<AdminRisk | "All">("All");
  const [service, setService] = useState("All services");
  const [query, setQuery] = useState("");
  const [justification, setJustification] = useState("");
  const selected = activities.find((item) => item.id === selectedId) ?? activities[0];
  const services = useMemo(() => ["All services", ...new Set(activities.map((item) => item.service))], [activities]);
  const filtered = useMemo(() => activities.filter((item) => (risk === "All" || item.risk === risk) && (service === "All services" || item.service === service) && `${item.administrator} ${item.action} ${item.target} ${item.center}`.toLowerCase().includes(query.toLowerCase())), [activities, risk, service, query]);
  const high = activities.filter((item) => item.risk === "High" || item.risk === "Critical").length;
  const failed = activities.filter((item) => item.result === "Failed").length;
  const approvals = activities.filter((item) => item.governance === "Approval required").length;
  const addEvidence = (event: string, detail: string, type: GovernanceAudit["type"]) => setGovernanceAudit((items) => [{ id: `local-${Date.now()}`, at: timestamp(), actor: "Governance analyst (demo)", event, detail, type }, ...items]);
  const updateGovernance = (next: AdminGovernance) => {
    if (next === "Approved" && !justification.trim()) { notify("Business justification is required before approving this critical administrative action."); return; }
    setActivities((items) => items.map((item) => item.id === selected.id ? { ...item, governance: next } : item));
    addEvidence(next === "Approved" ? "Administrative change approved" : "Administrative change rejected", `${selected.id}: ${selected.action} on ${selected.target}. ${justification.trim() || "No justification recorded."}`, "Approval");
    setJustification(""); notify(`${selected.id} governance decision recorded with audit evidence.`);
  };
  const report = (name: string, filter: (item: AdminActivity) => boolean) => { const selection = activities.filter(filter); downloadCsv(selection, name); addEvidence("Compliance report generated", `${name} contains ${selection.length} administrator activities.`, "Report"); notify(`${name} downloaded with ${selection.length} records.`); };

  return <section className="aga" data-testid="portal-admin-audit">
    <header className="pr-page-head aga-head"><div><span className="pr-kicker">SECURITY, COMPLIANCE & GOVERNANCE / PURVIEW AUDIT</span><h1>Microsoft 365 Administrator Activity Audit</h1><p>Cross-service governance evidence for administrative activity from Microsoft 365, Entra, Defender, Intune, Exchange, SharePoint, Teams, Purview, and Azure administration surfaces.</p></div><div className="aga-head-actions"><span className="aga-live"><i /> Audit ingestion healthy · 2 min ago</span><button className="pr-btn pr-primary" onClick={() => { setTab("reports"); report("daily-administrator-activity.csv", () => true); }} data-testid="aga-daily-export"><ArrowDownload24Regular /> Daily report</button></div></header>
    <div className="aga-metrics"><Metric label="Admin activities" value={activities.length} note="all connected admin centers" /><Metric label="High-risk changes" value={high} note="critical or high governance risk" tone="critical" /><Metric label="Failed operations" value={failed} note="requires review" tone="critical" /><Metric label="Pending approvals" value={approvals} note="critical changes awaiting decision" tone="amber" /><Metric label="Suspicious behaviour" value="3" note="travel, bulk change, config drift" tone="amber" /><Metric label="Compliance evidence" value="100%" note="events retained with audit history" tone="good" /></div>
    <div className="aga-integrations">{auditIntegrations.map(([name, status]) => <span key={name}><CloudCheckmark24Regular /> {name}<b>{status}</b></span>)}</div>
    <div className="aga-layout">
      <aside className="aga-queue"><div className="aga-queue-head"><div><b>Administrator activity timeline</b><small>{filtered.length} matching operations</small></div><button onClick={() => { setRisk("All"); setService("All services"); setQuery(""); }}>Clear</button></div><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search administrator, action, target" data-testid="aga-search" /><div className="aga-filters">{risks.map((item) => <button key={item} className={risk === item ? "aga-filter-on" : ""} onClick={() => setRisk(item)} data-testid={`aga-filter-${item.toLowerCase()}`}>{item}</button>)}</div><select value={service} onChange={(e) => setService(e.target.value)} data-testid="aga-service-filter">{services.map((item) => <option key={item}>{item}</option>)}</select><div className="aga-activity-list">{filtered.map((item) => <button key={item.id} className={`aga-activity ${selected.id === item.id ? "aga-selected" : ""}`} onClick={() => { setSelectedId(item.id); setTab("activity"); }} data-testid={`aga-event-${item.id}`}><span className={riskClass(item.risk)}>{item.risk}</span><b>{item.action}</b><small>{item.service} · {item.administrator}</small><footer><span>{item.timestamp}</span><span className={item.result === "Failed" ? "aga-failed" : ""}>{item.result}</span></footer></button>)}{filtered.length === 0 && <div className="aga-empty">No activity matches the selected filters.</div>}</div></aside>
      <article className="aga-detail"><div className="aga-hero"><div><span className={riskClass(selected.risk)}>{selected.risk}</span><span className="aga-id">{selected.id}</span><h2>{selected.action}</h2><p>{selected.target}</p></div><div><span>Governance state</span><b>{selected.governance}</b><small>{selected.center}</small></div></div><div className="aga-facts"><Fact label="Administrator" value={selected.administrator} /><Fact label="Timestamp / result" value={`${selected.timestamp} · ${selected.result}`} /><Fact label="Source IP / location" value={`${selected.ip} · ${selected.location}`} /><Fact label="Change category" value={selected.category} /></div><div className="aga-tabs" role="tablist">{(["activity", "comparison", "governance", "reports"] as AuditTab[]).map((item) => <button key={item} className={tab === item ? "aga-tab-on" : ""} onClick={() => setTab(item)} role="tab" aria-selected={tab === item}>{item === "activity" ? "Activity detail" : item === "comparison" ? "Before / after" : item[0].toUpperCase() + item.slice(1)}</button>)}</div>
        {tab === "activity" && <div className="aga-tab-content"><div className="aga-recommend"><Warning24Regular /><span><b>Administrative activity intelligence</b>Correlated with linked tenant audit events, privileged account monitoring, and change-governance controls.</span><button className="pr-btn" onClick={() => onOpenReport(selected.reportId)} data-testid="aga-open-report">Open supporting report <ArrowRight24Regular /></button></div><div className="aga-two-col"><Panel title="Activity evidence"><dl className="aga-dl"><dt>Admin center</dt><dd>{selected.center}</dd><dt>Service</dt><dd>{selected.service}</dd><dt>Business justification</dt><dd>{selected.reason}</dd><dt>Related control</dt><dd>Governed administrative change / audit retention</dd></dl></Panel><Panel title="Anomaly correlation"><ul className="aga-signals"><li><Warning24Regular /><span><b>Privileged activity monitoring</b>Role and policy changes correlated with identity-risk signals.</span></li><li><History24Regular /><span><b>Bulk modification detection</b>Checks change volume by administrator and service window.</span></li><li><ShieldCheckmark24Regular /><span><b>Unauthorised configuration detection</b>Compares changes against approval and CAB evidence.</span></li></ul></Panel></div><Panel title="Recent privileged actions"><div className="aga-privileged">{activities.filter((item) => item.category === "Privileged role" || item.risk === "Critical").slice(0, 4).map((item) => <div key={item.id}><span className={riskClass(item.risk)}>{item.risk}</span><b>{item.action}</b><small>{item.administrator} → {item.target}</small></div>)}</div></Panel></div>}
        {tab === "comparison" && <div className="aga-tab-content"><div className="aga-compare"><header><b>Before vs after configuration comparison</b><span>Hash-linked evidence version · {selected.id}</span></header><div><section><span>Previous value</span><pre>{selected.previous}</pre></section><i>→</i><section><span>New value</span><pre>{selected.current}</pre></section></div><footer><CheckmarkCircle24Regular /> Captured from {selected.center}; retained with administrator, timestamp, IP, result, and business rationale.</footer></div><div className="aga-impact"><Panel title="Risk analysis"><p><b>{selected.risk} risk</b> based on privilege level, service sensitivity, scope of affected resources, and governance state.</p><p>Correlations include impossible travel, emergency-admin activity, bulk modification patterns, and failed-operation sequences.</p></Panel><Panel title="Affected scope"><p><b>Target:</b> {selected.target}</p><p><b>Responsible admin:</b> {selected.administrator}</p><p><b>Service boundary:</b> {selected.service}</p></Panel></div></div>}
        {tab === "governance" && <div className="aga-tab-content"><div className="aga-governance"><LockClosed24Regular /><span><b>Approval and governance workflow</b>Critical changes require a business justification, approver decision, and immutable evidence trail. This local demo records the workflow but never changes a tenant.</span></div><div className="aga-two-col"><Panel title="Decision record"><label>Business justification<textarea value={justification} onChange={(e) => setJustification(e.target.value)} placeholder="Reference an incident, CAB, emergency change, or business requirement" data-testid="aga-justification" /></label><div className="aga-decision"><button className="pr-btn pr-primary" onClick={() => updateGovernance("Approved")} data-testid="aga-approve">Approve change</button><button className="pr-btn pr-danger" onClick={() => updateGovernance("Rejected")} data-testid="aga-reject">Reject change</button></div></Panel><Panel title="Current governance evidence"><dl className="aga-dl"><dt>State</dt><dd>{selected.governance}</dd><dt>Approver queue</dt><dd>Security Governance / CAB</dd><dt>Evidence retained</dt><dd>Before/after, administrator, IP, justification, decision</dd><dt>Ticketing</dt><dd>ServiceNow SIR linked in connected deployment</dd></dl></Panel></div><Panel title="Audit & compliance tracking"><div className="aga-audit" data-testid="aga-audit">{governanceAudit.slice(0, 12).map((item) => <div key={item.id}><ClipboardTask24Regular /><span><b>{item.event}</b><small>{item.at} · {item.actor} · {item.type}</small><p>{item.detail}</p></span></div>)}</div></Panel></div>}
        {tab === "reports" && <div className="aga-tab-content"><div className="aga-report-grid"><Report title="Daily administrator activity" description="Complete multi-service administrator activity with before/after values." run={() => report("daily-administrator-activity.csv", () => true)} testid="aga-report-daily" /><Report title="Weekly privileged access" description="Role assignments, privileged actions, and emergency admin events." run={() => report("weekly-privileged-access.csv", (item) => item.category === "Privileged role" || item.risk === "Critical")} testid="aga-report-privileged" /><Report title="Monthly compliance audit" description="Compliance and governance evidence across all Microsoft 365 admin centers." run={() => report("monthly-compliance-audit.csv", () => true)} testid="aga-report-compliance" /><Report title="Failed administrative actions" description="Failure evidence and unapproved or suspicious administrative operations." run={() => report("failed-administrative-actions.csv", (item) => item.result === "Failed")} testid="aga-report-failed" /><Report title="High-risk changes" description="Critical and high-risk configuration, permission, and security changes." run={() => report("high-risk-administrative-changes.csv", (item) => item.risk === "High" || item.risk === "Critical")} testid="aga-report-high-risk" /><Report title="Emergency admin activities" description="Critical privileged and emergency response actions for review." run={() => report("emergency-admin-activities.csv", (item) => item.reason.toLowerCase().includes("emergency") || item.risk === "Critical")} testid="aga-report-emergency" /></div><Panel title="Connected audit sources"><div className="aga-integration-list">{auditIntegrations.map(([name, state, detail]) => <div key={name}><CloudCheckmark24Regular /><span><b>{name}</b><small>{detail}</small></span><em>{state}</em></div>)}</div></Panel></div>}
      </article>
    </div>
  </section>;
}

function Metric({ label, value, note, tone = "blue" }: { label: string; value: string | number; note: string; tone?: string }) { return <div className={`aga-metric aga-tone-${tone}`}><span>{label}</span><b>{value}</b><small>{note}</small></div>; }
function Fact({ label, value }: { label: string; value: string }) { return <div><span>{label}</span><b>{value}</b></div>; }
function Panel({ title, children }: { title: string; children: ReactNode }) { return <section className="aga-panel"><h3>{title}</h3>{children}</section>; }
function Report({ title, description, run, testid }: { title: string; description: string; run: () => void; testid: string }) { return <div className="aga-report"><b>{title}</b><small>{description}</small><button className="pr-btn" onClick={run} data-testid={testid}><ArrowDownload24Regular /> Export CSV</button></div>; }
