import type { GeneratedReport } from "@/lib/reporting";

const API = "/api/runtime";

async function request<T>(
  path: string,
  init?: RequestInit,
): Promise<T> {
  const response = await fetch(`${API}${path}`, {
    ...init,
    headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) },
  });
  if (!response.ok) {
    const body = await response
      .json()
      .catch(() => ({ message: response.statusText }));
    throw new Error(
      Array.isArray(body.message)
        ? body.message.join(", ")
        : body.message || `API request failed (${response.status})`,
    );
  }
  return response.json() as Promise<T>;
}

export type RuntimeAdminCenter = {
  workload: string;
  total: number;
  healthy: number;
  warning: number;
  critical: number;
  health: number;
  averageRisk: number;
  freshnessSeconds: number;
};

export async function getAdminCenters() {
  return request<{ generatedAt: string; items: RuntimeAdminCenter[] }>(
    "/api/v1/admin-centers",
  );
}

type RuntimeReportJob = {
  id: string;
  name: string;
  workload: string;
  status: "queued" | "running" | "completed" | "failed";
  createdAt: string;
  completedAt?: string;
  progress: number;
  result?: {
    totalRows: number;
    columns: string[];
    rows: string[][];
    metrics: GeneratedReport["metrics"];
  };
  error?: string;
};

const delay = (milliseconds: number) =>
  new Promise((resolve) => setTimeout(resolve, milliseconds));

export async function runRuntimeReport(
  name: string,
  workload: string,
  columns?: string[],
): Promise<GeneratedReport> {
  let job = await request<RuntimeReportJob>("/api/v1/report-jobs", {
    method: "POST",
    body: JSON.stringify({ name, workload, columns }),
  });
  for (
    let attempt = 0;
    attempt < 40 && job.status !== "completed" && job.status !== "failed";
    attempt++
  ) {
    await delay(150);
    job = await request<RuntimeReportJob>(`/api/v1/report-jobs/${job.id}`);
  }
  if (job.status !== "completed" || !job.result)
    throw new Error(
      job.error ?? "Report job did not complete within the acceptance timeout.",
    );
  return {
    id: job.id,
    name: job.name,
    workload: job.workload,
    description:
      "Generated by the persistent local report-job runtime from seeded tenant resources.",
    generatedAt: job.completedAt ?? job.createdAt,
    sourceFreshness: "real-time local runtime",
    totalRows: job.result.totalRows.toLocaleString("en-US"),
    columns: job.result.columns,
    rows: job.result.rows,
    metrics: job.result.metrics,
  };
}

export type RuntimeWorkflow = {
  id: string;
  title: string;
  requestedBy: string;
  approver?: string;
  state:
    | "draft"
    | "pending_approval"
    | "approved"
    | "running"
    | "completed"
    | "failed"
    | "rolled_back";
  execution?: {
    affected: number;
    succeeded: number;
    failed: number;
    message: string;
  };
};

export async function getRuntimeWorkflows() {
  return request<{ items: RuntimeWorkflow[] }>("/api/v1/workflows");
}

export async function transitionRuntimeWorkflow(id: string, action: "approve" | "execute" | "rollback") {
  return request<RuntimeWorkflow>(`/api/v1/workflows/${id}/${action}`, { method: "POST", body: "{}" });
}

export async function runRuntimeWorkflow(
  title: string,
  targetScope: string,
  justification: string,
) {
  let workflow = await request<RuntimeWorkflow>(
    "/api/v1/workflows",
    {
      method: "POST",
      body: JSON.stringify({
        title,
        type: "governed-demo-operation",
        targetScope,
        justification,
      }),
    },
  );
  workflow = await request<RuntimeWorkflow>(
    `/api/v1/workflows/${workflow.id}/submit`,
    { method: "POST", body: "{}" },
  );
  return workflow;
}

export function runtimeEventUrl() {
  return `${API}/api/v1/events/stream`;
}
